language: php
php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"
  - "nightly"
env:
  - VERSION=3.6
  - VERSION=3.7
  - VERSION=3.8
  - VERSION=4.0
install:
  - "composer require orchestra/testbench:${VERSION}" --no-update
  - "composer install --ignore-platform-reqs"
