language: php
php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"
  - "nightly"
env:
  - VERSION=3.6
  - VERSION=3.7
  - VERSION=3.8
  - VERSION=4.0
  - VERSION=5.0
install:
  - "composer require ocramius/package-versions:1.4 --no-update --ignore-platform-reqs"
  - "composer require orchestra/testbench:${VERSION} --no-update --ignore-platform-reqs"
  - "composer install --ignore-platform-reqs"
jobs:
  allow_failures:
    - php: nightly
    - env: "VERSION=5.0"


